import React, { useState } from "react";
import styles from "./FunctionBuilder.module.css";
import { IoClose } from "react-icons/io5";
import FunctionParameterTable from "./FunctionParameterTable";
import CodeEditor from "./CodeEditor";
import FunctionResponse from "./FunctionResponse";

const FunctionBuilder = ({ toggleFunctionSideBar, parameters, 
  setParameters, functionMapList, setFunctionMapList}) => {

    const [ testResponse, setTestResponse ] = useState(null);



    // const removeCountryCode = (phoneNumber, countryCode) => {
    //     if (!phoneNumber.startsWith(countryCode)) {
    //       return phoneNumber;
    //     }
    //     return phoneNumber.slice(countryCode.length);
    //   };

      


  function getTestResponse(result){
    console.log("test response in parents: ", result);
    setTestResponse(result);

  }


  return (
    <div className={styles.funcctionBuilderModelContainer}>
      <div className={styles.functionBuilderWrapperContainer}>
        <IoClose
          onClick={() => toggleFunctionSideBar()}
          className={styles.closedFunctionModelIcon}
        />

        <FunctionParameterTable
         parameters={parameters}
         setParameters={setParameters} />

        <div className={styles.functionBodyContainer}>
          <div className={styles.functionLibrayContainer}>
            <p>library:</p>

            <div className={styles.libraryDropInputBox}>
              <input type="text" placeholder="Load additional js libraries" />
            </div>

            <div className={styles.tryGeneratedByAiButton}>
              <span>🔥</span>
              <p>Try Generated by AI</p>
            </div>
          </div>
        </div>

        <CodeEditor functionName="calculateSum"
         parameters={parameters}
          setParameters={setParameters}
          getTestResponse={getTestResponse} />

          { testResponse && (
            <FunctionResponse testResponse={testResponse}  functionMapList={functionMapList} 
            setFunctionMapList={setFunctionMapList} />

          )}

        
      </div>
    </div>
  );
};

export default FunctionBuilder;
